### ISSUE TITLE
After installation error received when running PairGPTWrite `attempt to concatenate field 'model'`

### ISSUE THREAD

**Issue by chknlittle** [naps62/pair-gpt.nvim#4]
Installed the vim plugin, set the api key env variable in `.zshrc`, installed the cargo package, ran `:PluginInstall`, sourced the changed `.zshrc` and restarted vim.

Ran the write command on following line in a .ts file
```
// first n fibbonaci numbers as array
```

Received the following error
```
E5108: Error executing lua /home/rin/.vim/bundle/pair-gpt.nvim/lua/pair-gpt.lua:36: attempt to concatenate field 'model' (a nil value
)
stack traceback:
        /home/rin/.vim/bundle/pair-gpt.nvim/lua/pair-gpt.lua:36: in function 'pair_cmd'
        /home/rin/.vim/bundle/pair-gpt.nvim/lua/pair-gpt.lua:83: in function 'write'
        [string ":lua"]:1: in main chunk
```

**Comment by chknlittle** [comment]
Problem solved.

Am using vim-plug, so (optional) configuration section is needed.

If you don't have a `~/.config/nvim/init.lua` setup, you can follow this guide to set it up:
https://herrbischoff.com/2022/07/neovim-using-init-vim-and-init-lua-concurrently/

In short, create the file `~/.config/nvim/init.lua.vim`
Add the configuration line
```
lua <<EOF
require("pair-gpt").setup()
EOF
```

Source the new lua init file in your `~/.config/nvim/init.vim` file by appending:
```
source $HOME/.config/nvim/init.lua.vim
```

**Comment by naps62** [comment]
Reopening so I don't forget to commit this later. Thanks 😄

**Comment by naps62** [comment]
Fixed
